//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arc.YTSubConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arc.YTSubConverter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t left-align text with line breaks ({0}).
        /// </summary>
        internal static string CantLeftAlignTextWithLineBreaks0 {
            get {
                return ResourceManager.GetString("CantLeftAlignTextWithLineBreaks0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered or right-aligned text can have at most one line break ({0}).
        /// </summary>
        internal static string CenteredOrRightAlignedTextCanHaveAtMostOneLineBreak0 {
            get {
                return ResourceManager.GetString("CenteredOrRightAlignedTextCanHaveAtMostOneLineBreak0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered or right-aligned text with line breaks must be top- or bottom-aligned ({0}).
        /// </summary>
        internal static string CenteredOrRightAlignedTextWithLineBreaksMustBeTopOrBottomAligned0 {
            get {
                return ResourceManager.GetString("CenteredOrRightAlignedTextWithLineBreaksMustBeTopOrBottomAligned0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Checkers {
            get {
                object obj = ResourceManager.GetObject("Checkers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag&amp;drop .ass/.sbv file or click the &quot;...&quot; button.
        /// </summary>
        internal static string DragNDropTip {
            get {
                return ResourceManager.GetString("DragNDropTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file: {0}.
        /// </summary>
        internal static string FailedToLoadFile0 {
            get {
                return ResourceManager.GetString("FailedToLoadFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced SubStation Alpha|*.ass|YouTube subtitles|*.sbv.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        internal static string Glow {
            get {
                return ResourceManager.GetString("Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard shadow.
        /// </summary>
        internal static string HardShadow {
            get {
                return ResourceManager.GetString("HardShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight current word.
        /// </summary>
        internal static string HighlightCurrentWord {
            get {
                return ResourceManager.GetString("HighlightCurrentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid color.
        /// </summary>
        internal static string IsNotAValidColor {
            get {
                return ResourceManager.GetString("IsNotAValidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid timestamp.
        /// </summary>
        internal static string IsNotAValidTimestamp {
            get {
                return ResourceManager.GetString("IsNotAValidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline color:.
        /// </summary>
        internal static string KaraokeOutlineColor {
            get {
                return ResourceManager.GetString("KaraokeOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow color:.
        /// </summary>
        internal static string KaraokeShadowColor {
            get {
                return ResourceManager.GetString("KaraokeShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color:.
        /// </summary>
        internal static string KaraokeTextColor {
            get {
                return ResourceManager.GetString("KaraokeTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a .
        /// </summary>
        internal static string PreviewSampleKaraoke1 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample .
        /// </summary>
        internal static string PreviewSampleKaraoke2 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string PreviewSampleKaraoke3 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample text.
        /// </summary>
        internal static string PreviewSampleRegular {
            get {
                return ResourceManager.GetString("PreviewSampleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow types:.
        /// </summary>
        internal static string ShadowTypes {
            get {
                return ResourceManager.GetString("ShadowTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft shadow.
        /// </summary>
        internal static string SoftShadow {
            get {
                return ResourceManager.GetString("SoftShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style options.
        /// </summary>
        internal static string StyleOptions {
            get {
                return ResourceManager.GetString("StyleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0}.
        /// </summary>
        internal static string SuccessfullyCreated0 {
            get {
                return ResourceManager.GetString("SuccessfullyCreated0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for karaoke.
        /// </summary>
        internal static string UseForKaraoke {
            get {
                return ResourceManager.GetString("UseForKaraoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertically centered lines with multiple styles can&apos;t have line breaks ({0}).
        /// </summary>
        internal static string VerticallyCenteredLinesWithMultipleStylesCantHaveLineBreaks0 {
            get {
                return ResourceManager.GetString("VerticallyCenteredLinesWithMultipleStylesCantHaveLineBreaks0", resourceCulture);
            }
        }
    }
}
