//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arc.YTSubConverter {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arc.YTSubConverter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;StyleOptions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Style&gt;
        ///    &lt;Name&gt;YTPlain&lt;/Name&gt;
        ///    &lt;ShadowType&gt;None&lt;/ShadowType&gt;
        ///    &lt;IsKaraoke&gt;false&lt;/IsKaraoke&gt;
        ///    &lt;CurrentWordTextColor /&gt;
        ///    &lt;CurrentWordOutlineColor /&gt;
        ///    &lt;CurrentWordShadowColor /&gt;
        ///  &lt;/Style&gt;
        ///  &lt;Style&gt;
        ///    &lt;Name&gt;YTPlainBox&lt;/Name&gt;
        ///    &lt;ShadowType&gt;None&lt;/ShadowType&gt;
        ///    &lt;IsKaraoke&gt;false&lt;/IsKaraoke&gt;
        ///    &lt;CurrentWordTextColor /&gt;
        ///    &lt;CurrentWordOutlin [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultStyleOptions {
            get {
                return ResourceManager.GetString("DefaultStyleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] DefaultStyles {
            get {
                object obj = ResourceManager.GetObject("DefaultStyles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   {0} is not a valid color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsNotAValidColor {
            get {
                return ResourceManager.GetString("IsNotAValidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a valid timestamp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsNotAValidTimestamp {
            get {
                return ResourceManager.GetString("IsNotAValidTimestamp", resourceCulture);
            }
        }
    }
}
