//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arc.YTSubConverter {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arc.YTSubConverter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Autoconvert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Autoconvert {
            get {
                return ResourceManager.GetString("Autoconvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bevel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Bevel {
            get {
                return ResourceManager.GetString("Bevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Checkers {
            get {
                object obj = ResourceManager.GetObject("Checkers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Clear background image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearBackgroundImage {
            get {
                return ResourceManager.GetString("ClearBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;StyleOptions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Style&gt;
        ///    &lt;Name&gt;YTPlain&lt;/Name&gt;
        ///    &lt;ShadowType&gt;None&lt;/ShadowType&gt;
        ///    &lt;IsKaraoke&gt;false&lt;/IsKaraoke&gt;
        ///    &lt;CurrentWordTextColor /&gt;
        ///    &lt;CurrentWordOutlineColor /&gt;
        ///    &lt;CurrentWordShadowColor /&gt;
        ///  &lt;/Style&gt;
        ///  &lt;Style&gt;
        ///    &lt;Name&gt;YTPlainBox&lt;/Name&gt;
        ///    &lt;ShadowType&gt;None&lt;/ShadowType&gt;
        ///    &lt;IsKaraoke&gt;false&lt;/IsKaraoke&gt;
        ///    &lt;CurrentWordTextColor /&gt;
        ///    &lt;CurrentWordOutlin [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultStyleOptions {
            get {
                return ResourceManager.GetString("DefaultStyleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] DefaultStyles {
            get {
                object obj = ResourceManager.GetObject("DefaultStyles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Drag&amp;drop .ass/.sbv file or click the &quot;...&quot; button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DragNDropTip {
            get {
                return ResourceManager.GetString("DragNDropTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoadFile0 {
            get {
                return ResourceManager.GetString("FailedToLoadFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Glow {
            get {
                return ResourceManager.GetString("Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hard shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HardShadow {
            get {
                return ResourceManager.GetString("HardShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlight current word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HighlightCurrentWord {
            get {
                return ResourceManager.GetString("HighlightCurrentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images|*.gif;*.jpg;*.jpeg;*.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a valid color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsNotAValidColor {
            get {
                return ResourceManager.GetString("IsNotAValidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a valid timestamp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsNotAValidTimestamp {
            get {
                return ResourceManager.GetString("IsNotAValidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outline color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KaraokeOutlineColor {
            get {
                return ResourceManager.GetString("KaraokeOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KaraokeShadowColor {
            get {
                return ResourceManager.GetString("KaraokeShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KaraokeTextColor {
            get {
                return ResourceManager.GetString("KaraokeTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewSampleKaraoke1 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sample  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewSampleKaraoke2 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewSampleKaraoke3 {
            get {
                return ResourceManager.GetString("PreviewSampleKaraoke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewSampleRegular {
            get {
                return ResourceManager.GetString("PreviewSampleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select background image... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBackgroundImage {
            get {
                return ResourceManager.GetString("SelectBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow types: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShadowTypes {
            get {
                return ResourceManager.GetString("ShadowTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soft shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftShadow {
            get {
                return ResourceManager.GetString("SoftShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Style options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StyleOptions {
            get {
                return ResourceManager.GetString("StyleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced SubStation Alpha|*.ass|YouTube subtitles|*.sbv;*.srv3;*.ytt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubtitleFileFilter {
            get {
                return ResourceManager.GetString("SubtitleFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully created {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessfullyCreated0 {
            get {
                return ResourceManager.GetString("SuccessfullyCreated0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use for karaoke に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseForKaraoke {
            get {
                return ResourceManager.GetString("UseForKaraoke", resourceCulture);
            }
        }
    }
}
